### ISSUE TITLE
my opinion on some code

### ISSUE THREAD

**Issue by AverageDaveLover65** [EIT0/Psych-Engine-Tutorials#33]
some of it sucks, i could probably try revamping it with my own code, but then people wont credit me so i wont do that
for example, the char select state kinda sucks tbh, dnb one is better.
and also some of the code in some of the states.

**Comment by AverageDaveLover65** [comment]
please DO NOT take this serious

**Comment by EIT0** [comment]
Ik, im lazy, code lazier think smarter
